import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import { FaLinkedin, FaXTwitter, FaFacebook } from "react-icons/fa6";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <footer className="w-full bg-black py-10 text-white">
          <div className="max-w-6xl mx-auto px-4 flex flex-col items-center">
            <div className="w-full flex flex-col md:flex-row items-center justify-center gap-12 mb-4 relative">
              <div className="flex flex-1 justify-center gap-6">
                <Link href="/about">About Us</Link>
                <Link href="/projects">Projects</Link>
                <Link href="/contact">Contact</Link>
              </div>
              <div className="absolute right-0 top-1/2 -translate-y-1/2 flex gap-3">
                <a href="#" aria-label="Facebook">
                  <FaFacebook size={16} />
                </a>
                <a href="#" aria-label="LinkedIn">
                  <FaLinkedin size={16} />
                </a>
                <a href="#" aria-label="X">
                  <FaXTwitter size={16} />
                </a>
              </div>
            </div>
            <hr className="border-white/40 mb-4 w-full" />
            <div className="flex flex-col md:flex-row items-center justify-center text-sm gap-8">
              <div>Copyright © 2025 Inspiralor. All rights reserved.</div>
              <Link href="/terms">Terms and Conditions</Link>
              <Link href="/privacy">Privacy Policy</Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
